
services:
  db:
    image: postgres:17
    container_name: notion_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notion_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: >
      sh -c "sleep 40 && 
             alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
#    environment:
#      DATABASE_URL: postgresql://postgres:0000@db:5432/notion_db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data: